# Exported from:        http://Kirans-MacBook-Pro.local:5516/
# Release version:      24.1.0
# Date created:         Fri Nov 07 11:45:32 CET 2025

---
apiVersion: xl-release/v1
kind: Import
spec:
  imports:
  - Notifications.yaml
  - Template_template_t1.yaml
