# Exported from:        http://Kirans-MacBook-Pro.local:5516/
# Release version:      24.1.0

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  path: A/B
  home: S-127327/A/B
spec:
- template: Test_CRT
  scheduledStartDate: 2025-12-22T04:30:00+01:00
  dueDate: 2025-12-22T05:30:00+01:00
  phases:
  - phase: New Phase
    tasks:
    - name: CRT1
      type: xlrelease.CreateReleaseTask
      newReleaseTitle: RAC
      template: ./A/T1A
      folder: ./
  riskProfile: Default risk profile
  author: admin
