# Exported from:        http://Kirans-MacBook-Pro.local:5516/
# Release version:      24.1.0
# Date created:         Thu Nov 06 10:49:37 CET 2025

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  path: /
  home: Test-Folder
spec:
- template: T1
  scheduledStartDate: 2025-11-06T04:30:00+01:00
  phases:
  - phase: New Phase
  riskProfile: Default risk profile
  author: admin
