# Exported from:        http://DESKTOP-9DGBIAE:5516/
# Release version:      23.1.0
# Date created:         Fri Nov 17 15:23:31 IST 2023

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: D-27244
spec:
- name: test-endpoint
  type: events.PostWebhookEndpoint
  path: test-trigger-endp
  authentication:
    type: events.NoAuthentication
- name: Jenkins-Folder
  type: jenkins.Server
  url: http://localhost:8082
  username: admin
  password: !value "jenkins_Server_Jenkins_Folder_password"
- template: D-27244_Create_Release_Template
  scheduledStartDate: 2023-11-06T09:00:00+05:30
  phases:
  - phase: Phase One
    tasks:
    - name: T1
      type: xlrelease.ScriptTask
      script: |-
        from com.xebialabs.xlrelease.api.v1.forms import CreateRelease

        for x in range(1300):
            folderId = 'Applications/Folderdbd784955c1a43aea694bfa176e4e698'
            templateId = 'Applications/Folderdbd784955c1a43aea694bfa176e4e698/Release7dfb323b5632469db5820ed2e18b75da'
            releaseName = 'Jenkins_Release-v2-'+str(x)
            print "Release Name %s" % (releaseName)
            createRelease = CreateRelease(releaseName, folderId, {}, {})

            print "Creating release %s" % (releaseName)

            release = templateApi.create(templateId, createRelease)
    color: '#3d6c9e'
  scriptUsername: admin
  scriptUserPassword: !value "xlrelease_Release_D_27244_Create_Release_Template_scriptUserPassword"
  riskProfile: Default risk profile
  author: admin
  defaultTargetFolder: ./
- template: D-27244_Jenkins-Template
  scheduledStartDate: 2023-11-06T09:00:00+05:30
  phases:
  - phase: Phase 01
    tasks:
    - name: T1
      type: jenkins.Build
      jenkinsServer: Jenkins-Folder
      username: admin
      password: !value "jenkins_Build_T1_password"
      jobName: Test
    color: '#3d6c9e'
  scriptUsername: admin
  scriptUserPassword: !value "xlrelease_Release_D_27244_Jenkins_Template_scriptUserPassword"
  riskProfile: Default risk profile
  author: admin
  defaultTargetFolder: ./
- name: test-trigger
  type: events.EventBasedTrigger
  enabled: false
  mappedProperties:
  - type: xlrelease.StringValue
    targetProperty: releaseTitle
    value: Test-Release
  - type: xlrelease.StringValue
    targetProperty: template
    value: D-27244_Create_Release_Template
  - type: xlrelease.StringValue
    targetProperty: releaseFolder
    value: ./
  triggerActionType: xlrelease.CreateReleaseFromTemplateAction
  eventSource: test-endpoint
  eventType: events.HttpRequestEvent
- notifications:
  - notification: TASK_OVERDUE
    priority: High
    subject: "[Release] ${release.title}: ${task.title}"
    body: |-
      The **${task.title}** task in the **${release.title}** release is overdue.

      After the task is completed, please mark it as Completed in Release.
    roles:
    - Watcher
    - Release Admin
    - Task Owner
  - notification: TASK_FLAGGED
    priority: High
    subject: "[Release] ${release.title}: ${task.title}"
    body: |-
      The status of the **${task.title}** task in the **${release.title}** release was changed to **${task.flagStatus}** with the following comment:

      **${release.flagComment}**
    roles:
    - Watcher
    - Release Admin
    - Task Team
  - notification: AUDIT_REPORT_JOB_ABORTED
    priority: Normal
    subject: "[Release] Audit report was aborted"
    body: |-
      **Your audit report was aborted!**

       Please try to generate it again or contact your Release administrator for assistance.
  - notification: MANUAL_TASK_STARTED
    priority: Normal
    subject: "[Release] ${release.title}: ${task.title}"
    body: |-
      The **${task.title}** task in the **${release.title}** release has started and is assigned to you or your team.

      After the task is completed, please mark it as Completed in Release.
    roles:
    - Watcher
    - Task Owner
  - notification: TASK_FAILED
    priority: High
    subject: "[Release] ${release.title}: ${task.title}"
    body: |-
      The **${task.title}** task in the **${release.title}** release has failed.

      Other tasks could still be in progress, but the release will stop after they complete.

      You can retry the task, reassign it to somebody else or abort the release.
    roles:
    - Watcher
    - Task Team
    - Task Owner
  - notification: USER_MENTIONED
    priority: Normal
    subject: "[Release] ${mentionedByFullName} mentioned you on ${release.title}:\
      \ ${task.title}"
    body: "**${mentionedByFullName}** mentioned you on the **${task.title}** task\
      \ in the **${release.title}** release:"
  - notification: COMMENT_ADDED
    priority: Normal
    subject: "[Release] ${release.title}: ${task.title}"
    body: |-
      **${comment.authorFullName}** commented on the **${task.title}** task in the **${release.title}** release:

      ${comment.text}
    roles:
    - Watcher
    - Task Team
    - Task Owner
  - notification: AUDIT_REPORT_JOB_FAILED
    priority: Normal
    subject: "[Release] Audit report has failed"
    body: |-
      **Your audit report has failed!**

       Please try to generate it again or contact your Release administrator for assistance.
  - notification: RELEASE_FAILED
    priority: High
    subject: "[Release] ${release.title}"
    body: |-
      The **${release.title}** release has failed due to a task failure.

      The release is now stopped.

      You can retry the failed task, reassign it to somebody else or abort the release.
    roles:
    - Release Admin
  - notification: TASK_DUE_SOON
    priority: Normal
    subject: "[Release] ${release.title}: ${task.title}"
    body: |-
      The **${task.title}** task in the **${release.title}** release is due in **${task.dueInHours}** hours and **${task.dueInMinutes}** minutes.

      After the task is completed, please mark it as Completed in Release.
    roles:
    - Watcher
    - Release Admin
    - Task Owner
  - notification: ACTIVE_TASK_UNASSIGNED
    priority: Normal
    subject: "[Release] ${release.title}: ${task.title}"
    body: |-
      The **${task.title}** task in the **${release.title}** release is active but not assigned to anyone anymore.

      Please assign the task to a user or a team.
    roles:
    - Watcher
    - Task Team
    - Task Owner
  - notification: RELEASE_FAILING
    priority: High
    subject: "[Release] ${release.title}"
    body: |-
      The **${release.title}** release is failing due to a task failure.

      Other tasks may still be in progress, but the release will stop after they complete.

      You can retry the failed task, reassign it to somebody else or abort the release.
    roles:
    - Release Admin
  - notification: USER_TOKEN_ABOUT_TO_EXPIRE
    priority: Normal
    subject: "[Release] Your personal access token is about to expire"
    body: |-
      Your personal access token "'${token.tokenNote}'" will expire in about ${token.expirationDurationInHours} hours.

       If this token is still needed, visit [Access tokens](${url}#/personal-access-token) to generate an equivalent.
  - notification: RELEASE_FLAGGED
    priority: High
    subject: "[Release] ${release.title}"
    body: |-
      The status of the **${release.title}** release was changed to **${release.flagStatus}** with the following comment:

      **${release.flagComment}**
    roles:
    - Release Admin
  - notification: MANUAL_TASK_STARTED_WITHOUT_OWNER
    priority: Normal
    subject: "[Release] ${release.title}: ${task.title}"
    body: |-
      The **${task.title}** task in the **${release.title}** release has started, but it is not assigned.

      Please assign the task to a user or a team.
    roles:
    - Watcher
    - Release Admin
  - notification: RELEASE_COMPLETED
    priority: Normal
    subject: "[Release] ${release.title}"
    body: "The **${release.title}** release has been completed."
    roles:
    - Release Admin
  - notification: TASK_WAITING_FOR_INPUT
    priority: Normal
    subject: "[Release] ${release.title}: ${task.title}"
    body: |-
      The **${task.title}** task in the **${release.title}** release needs your input.

      Please enter the required information so the release can continue.
    roles:
    - Watcher
    - Task Team
    - Task Owner
  - notification: AUDIT_REPORT_JOB_COMPLETED
    priority: Normal
    subject: "[Release] Report '${report.reportName}' is ready"
    body: |-
      **Your audit report is complete!**

       '${report.reportName}' is ready for download.
  - notification: GENERIC_SYSTEM_NOTIFICATION
    priority: Normal
    subject: "${notification.subject}"
    body: "${notification.body}"
  - notification: RELEASE_STARTED
    priority: Normal
    subject: "[Release] ${release.title}"
    body: "The **${release.title}** release has been started."
    bulkSubject: "[Release] Multiple releases started"
    bulkBody: |-
      The following releases have been started:

      ${#releases}
      * [${title}](${url})
      ${/releases}
    roles:
    - Release Admin
  - notification: RELEASE_ABORTED
    priority: Normal
    subject: "[Release] ${release.title}"
    body: "The **${release.title}** release has been aborted."
    bulkSubject: "[Release] Multiple releases aborted"
    bulkBody: |-
      The following releases have been aborted:

      ${#releases}
      * [${title}](${url})
      ${/releases}
    roles:
    - Release Admin
  - notification: ACTIVE_TASK_ASSIGNED
    priority: Normal
    subject: "[Release] ${release.title}: ${task.title}"
    body: "The active task **${task.title}** in the **${release.title}** release is\
      \ now assigned to ${task.ownerFullName}."
    roles:
    - Watcher
    - Task Team
    - Task Owner
