# Exported from:        http://release-nightly.devops.dev.digitalai.cloud/
# Release version:      26.1.0-beta.923
# Date created:         Wed Sep 24 11:48:10 GMT 2025

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  path: /
  home: D-41242%2F
spec:
- name: Test-Trigger///
  type: time.Schedule
  releaseTitle: RSAB
  template: Template_T1//
  releaseFolder: D-41242/
  periodicity: 0 0 9-17 * * MON-FRI
