# Exported from:        http://DESKTOP-9DGBIAE:5516/
# Release version:      23.1.0
# Date created:         Thu Jan 04 19:29:40 IST 2024

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: S-97036
spec:
- template: S-97036_T1
  scheduledStartDate: 2023-08-09T12:30:00+05:30
  dueDate: 2023-08-09T13:30:00+05:30
  phases:
  - phase: New Phase
    tasks:
    - name: Select User
      type: xlrelease.UserInputTask
      description: "Select the user, who is responsible for this stupid bug."
      owner: lrcufer
      variables:
      - user
    - name: STOP
      type: xlrelease.Task
  variables:
  - type: xlrelease.StringVariable
    key: user
    showOnReleaseStart: false
    label: Benutzer
    valueProvider:
      type: xlrelease.ListOfStringValueProviderConfiguration
      values:
      - Alexander Dobozanov
      - digital.ai
      - Geert Fiedler
      - Georg Hartl
      - Manuel Gülly
      - Markus Maier
      - Richard Schöner
      - Roland Feichtinger
  scriptUsername: admin
  scriptUserPassword: !value "xlrelease_Release_S_97036_T1_scriptUserPasswo"
  riskProfile: Default risk profile
  defaultTargetFolder: ./
