# Exported from:        http://DESKTOP-9DGBIAE:5516/
# Release version:      23.1.0
# Date created:         Thu Jan 04 19:29:40 IST 2024

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: S-97036
spec:
- template: T2
  scheduledStartDate: 2024-01-04T09:00:00+05:30
  phases:
  - phase: New Phase
    tasks:
    - name: T1
      type: xlrelease.Task
      owner: admin
  scriptUsername: admin
  scriptUserPassword: !value "xlrelease_Release_T2_scriptUserPassword"
  riskProfile: Default risk profile
  author: admin
  defaultTargetFolder: ./
