# Exported from:        http://Kirans-MacBook-Pro.local:5516/
# Release version:      26.1.6

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  path: /
  home: D-43333
spec:
- template: Parent_Template
  scheduledStartDate: 2026-07-01T09:00:00+05:30
  dueDate: 2026-07-01T10:00:00+05:30
  phases:
  - phase: New Phase
    tasks:
    - name: JT1
      type: xlrelease.ScriptTask
      owner: admin
      script: print 'Hello World'
  riskProfile: Default risk profile
  author: admin
