# Exported from:        http://Kirans-MacBook-Pro.local:5516/
# Release version:      24.1.0
# Date created:         Tue Jul 08 15:57:13 IST 2025

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  path: /
  home: Folder_Versioning_Hardening_25.3
spec:
- template: Test_Template_T2
  scheduledStartDate: 2025-07-08T09:00:00+05:30
  dueDate: 2025-07-08T10:00:00+05:30
  phases:
  - phase: New Phase
    tasks:
    - name: T1
      type: xlrelease.Task
  scriptUsername: admin
  scriptUserPassword: !value "xlrelease_Release_Test_Template_T2_scriptUserPassword"
  riskProfile: Default risk profile
  author: admin
