# Exported from:        http://Kirans-MacBook-Pro.local:5516/
# Release version:      24.1.0
# Date created:         Wed Sep 24 17:57:52 IST 2025

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  path: /
  home: D-41242-Test%2F
spec:
- name: Test-Trigger//
  type: time.Schedule
  releaseTitle: RAB
  template: Test-Template//
  releaseFolder: D-40773/
  periodicity: 0 0 9-17 * * MON-FRI
