# Exported from:        http://Kirans-MacBook-Pro.local:5516/
# Release version:      24.1.0
# Date created:         Tue Oct 07 14:58:20 IST 2025

---
apiVersion: xl-release/v1
kind: Applications
metadata:
  path: /
  home: S-116492-B
spec:
- name: App-01
  type: xlrelease.Application
  environments:
  - Dev-Env
