# Exported from:        http://Kirans-MacBook-Pro.local:5516/
# Release version:      24.1.0
# Date created:         Thu Sep 25 11:33:21 IST 2025

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  path: /
  home: Test-Forward-Slash%2F%2F
spec:
- template: Test-Workflow//
  scheduledStartDate: 2025-09-25T09:00:00+05:30
  phases:
  - phase: Workflow tasks
  kind: WORKFLOW
  disableNotifications: true
  author: admin
  defaultTargetFolder: Test-Forward-Slash//
