# Exported from:        http://release-nightly.devops.dev.digitalai.cloud/
# Release version:      26.1.0-beta.1113
# Date created:         Thu Nov 13 09:03:59 GMT 2025

---
apiVersion: xl-release/v1
kind: Import
spec:
  imports:
  - Connections.yaml
  - Notifications.yaml
  - Permissions.yaml
