# Exported from:        http://Kirans-MacBook-Pro.local:5516/
# Release version:      24.1.0
# Date created:         Thu Oct 09 12:33:42 IST 2025

---
apiVersion: xl-release/v1
kind: Applications
metadata:
  path: /
  home: Test-S-116492-AppsAndEnv
spec:
- name: Dev-App
  type: xlrelease.Application
  environments:
  - Dev-Env
