# Exported from:        http://Kirans-MacBook-Pro.local:5516/
# Release version:      24.1.0
# Date created:         Thu Oct 09 12:50:37 IST 2025

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  path: /
  home: Test-S-116492-AppsAndEnv
spec:
- template: T1
  scheduledStartDate: 2025-10-09T09:00:00+05:30
  phases:
  - phase: New Phase
    tasks:
    - name: New task
      type: xlrelease.Task
  riskProfile: Default risk profile
  author: admin
