# Exported from:        http://Kirans-MacBook-Pro.local:5516/
# Release version:      24.1.0
# Date created:         Fri Nov 14 12:46:54 CET 2025

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  path: /
  home: D-40470
spec:
- template: T1
  scheduledStartDate: 2025-11-14T04:30:00+01:00
  phases:
  - phase: New Phase
    tasks:
    - name: T1
      type: xlrelease.Task
      owner: admin
  riskProfile: Default risk profile
  author: admin
