# Exported from:        http://LAPTOP-95VG3LUV:5516/
# Release version:      22.0.0-20211220-123974
# Date created:         Thu Apr 27 16:02:32 IST 2023

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: S-90701
spec:
- pattern: Test_Pattern P1
  plannedDuration: 1
  stages:
  - stage: Stage 0
    transition:
      name: New Transition
      type: delivery.Transition
      conditions:
      - type: delivery.ConditionGroup
        operator: OR
        conditions:
        - type: delivery.ConditionGroup
          operator: AND
          conditions:
          - type: delivery.TimeCondition
    owner: admin
  - stage: Stage 1
    owner: admin
