# Exported from:        http://LAPTOP-95VG3LUV:5516/
# Release version:      22.0.0-20211220-123974
# Date created:         Thu Apr 27 16:24:46 IST 2023

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: S-90701
spec:
- template: Test_Template (1)
  scheduledStartDate: 2023-04-27T09:00:00+05:30
  phases:
  - phase: Phase One
    tasks:
    - name: Task One
      type: xlrelease.Task
      owner: admin
    - name: Task Two
      type: xlrelease.Task
      owner: admin
    - name: Gate task
      type: xlrelease.GateTask
    color: '#3d6c9e'
  riskProfile: Default risk profile
