# Exported from:        http://Kirans-MacBook-Pro.local:5516/
# Release version:      24.1.0

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  path: /
  home: D-43333
spec:
- folderVariables:
  - type: xlrelease.StringVariable
    key: folder.releaseFolderPath
    value: Applications/Folder0bbf68199f484e758b5fe83625a8d1af
  - type: xlrelease.StringVariable
    key: folder.Template - Standard Change OPEN
    value: Applications/Folder0bbf68199f484e758b5fe83625a8d1af/Release1607b0280be142b6a232a69a2d360041
