# Exported from:        http://Kirans-MacBook-Pro.local:5516/
# Release version:      24.1.0

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  path: /
  home: D-43333
spec:
- folderVariables:
  - type: xlrelease.StringVariable
    key: folder.releaseFolderPath
    value: Applications/Foldera1ed976a4efa48b2b87980947ef17716
  - type: xlrelease.StringVariable
    key: folder.Template - Standard Change OPEN
    value: Applications/Foldera1ed976a4efa48b2b87980947ef17716/Release37c0786a5021487bb9f936f3d68531de
