# Exported from:        http://DESKTOP-9DGBIAE:5516/
# Release version:      23.1.0
# Date created:         Thu Nov 16 13:17:56 IST 2023

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: D-31811
spec:
- name: Jenkins-Folder
  type: jenkins.Server
  url: http://localhost:8082/
  username: admin
  password: !value "jenkins_Server_Jenkins_Folder_password"
