# Exported from:        http://DESKTOP-9DGBIAE:5516/
# Release version:      23.1.0
# Date created:         Thu Nov 16 13:17:56 IST 2023

---
apiVersion: xl-release/v1
kind: Import
spec:
  imports:
  - Connections.yaml
  - Notifications.yaml
  - Template_Test_Template_1.yaml
  - Workflow_Test_Workflow_Template.yaml
