# Exported from:        http://DESKTOP-9DGBIAE:5516/
# Release version:      23.1.0
# Date created:         Thu Nov 16 13:17:56 IST 2023

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: D-31811
spec:
- template: Test_Template_1
  scheduledStartDate: 2023-11-16T09:00:00+05:30
  phases:
  - phase: Phase 01
    tasks:
    - name: T1
      type: jenkins.Build
      jenkinsServer: Jenkins-Folder
      username: admin
      password: !value "jenkins_Build_T1_password"
      jobName: Test
    color: '#3d6c9e'
  scriptUsername: admin
  scriptUserPassword: !value "xlrelease_Release_Test_Template_1_scriptUserPassword"
  riskProfile: Default risk profile
  author: admin
  defaultTargetFolder: ./
