# Exported from:        http://DESKTOP-9DGBIAE:5516/
# Release version:      23.1.0
# Date created:         Thu Nov 16 13:17:56 IST 2023

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: D-31811
spec:
- template: Test_Workflow_Template
  scheduledStartDate: 2023-11-16T09:00:00+05:30
  phases:
  - phase: Workflow tasks
    tasks:
    - name: T1
      type: jenkins.Build
      jenkinsServer: Jenkins-Folder
      username: admin
      password: !value "jenkins_Build_T1_password"
      jobName: Test
    - name: T2
      type: jenkins.Build
      jenkinsServer: Jenkins-Folder
      username: admin
      password: !value "jenkins_Build_T2_password"
      jobName: Test
    - name: T3
      type: jenkins.Build
      jenkinsServer: Jenkins-Folder
      username: admin
      password: !value "jenkins_Build_T3_password"
      jobName: Test
  kind: WORKFLOW
  disableNotifications: true
  scriptUsername: admin
  scriptUserPassword: !value "xlrelease_Release_Test_Workflow_Template_scriptUserPassword"
  author: admin
  defaultTargetFolder: ./
