# Exported from:        http://Kirans-MacBook-Pro.local:5516/
# Release version:      24.1.0
# Date created:         Fri Nov 22 15:18:54 IST 2024

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  path: /
  home: Samples & Tutorials/Nested
spec:
- name: jenkins nested
  type: jenkins.Server
  url: http://test
