# Exported from:        http://Kirans-MacBook-Pro.local:5516/
# Release version:      24.1.0
# Date created:         Fri Nov 22 15:18:54 IST 2024

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  path: /
  home: Samples & Tutorials/Nested
spec:
- template: My template with reference
  scheduledStartDate: 2024-10-08T12:30:00+05:30
  dueDate: 2024-10-08T13:30:00+05:30
  phases:
  - phase: New Phase
    tasks:
    - name: New task
      type: jenkins.Build
      variableMapping:
        pythonScript.jenkinsServer: "${folder.reference}"
  variables:
  - type: xlrelease.ReferenceVariable
    key: reference
    value: Configuration/Custom/Configurationa81e23bba0104714b20d1311fcda43c2
    referencedType: jenkins.Server
  riskProfile: Default risk profile
  author: admin
