# Exported from:        http://Kirans-MacBook-Pro.local:5516/
# Release version:      24.1.0
# Date created:         Tue Nov 11 10:56:34 CET 2025

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  path: /
  home: S-125620
spec:
- template: T1.2
  scheduledStartDate: 2025-10-22T05:30:00+02:00
  dueDate: 2025-10-22T06:30:00+02:00
  phases:
  - phase: New Phase
    tasks:
    - name: New task
      type: xlrelease.Task
      owner: admin
    - name: New task
      type: xlrelease.Task
  riskProfile: Default risk profile
  author: admin
