# Exported from:        http://LAPTOP-95VG3LUV:5516/
# Release version:      22.0.0-20211220-123974
# Date created:         Wed Mar 15 13:29:04 IST 2023

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: Test-1
spec:
- pattern: Test_Pattern_Check
  description: Test_Pattern_Check
  plannedDuration: 1
  stages:
  - stage: Stage One
    owner: admin
  - stage: Stage 2
    owner: admin
