# Exported from:        http://LAPTOP-95VG3LUV:5516/
# Release version:      22.0.0-20211220-123974
# Date created:         Wed Mar 15 13:29:04 IST 2023

---
apiVersion: xl-release/v1
kind: Import
spec:
  imports:
  - Templates.yaml
  - Dashboards.yaml
  - Triggers.yaml
  - Patterns.yaml
  - Permissions.yaml
