# Exported from:        http://LAPTOP-95VG3LUV:5516/
# Release version:      22.0.0-20211220-123974
# Date created:         Tue Mar 07 12:14:56 IST 2023

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: Test-1
spec: []
