# Exported from:        http://LAPTOP-95VG3LUV:5516/
# Release version:      22.0.0-20211220-123974
# Date created:         Mon Mar 13 14:13:49 IST 2023

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: Test-1
spec:
- template: T1
  scheduledStartDate: 2023-03-09T09:00:00+05:30
  phases:
  - phase: P1
    tasks:
    - name: T1
      type: xlrelease.Task
    color: '#3d6c9e'
  riskProfile: Default risk profile
