# Exported from:        http://Kirans-MacBook-Pro.local:5516/
# Release version:      26.1.2

---
apiVersion: xl-release/v1
kind: Import
spec:
  imports:
  - Notifications.yaml
  - Template_crt_template.yaml
  - Template_parent_template.yaml
  - Variables.yaml
