# Exported from:        http://Kirans-MacBook-Pro.local:5516/
# Release version:      24.1.0
# Date created:         Thu Nov 13 09:46:30 CET 2025

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  path: /
  home: S-125072
spec:
- template: Test-One
  scheduledStartDate: 2025-11-12T04:30:00+01:00
  phases:
  - phase: New Phase
    tasks:
    - name: Jira-Check Issue
      type: jira.CheckIssue
    - name: Jenkins-Build
      type: jenkins.Build
  riskProfile: Default risk profile
  author: admin
