# Exported from:        http://Kirans-MacBook-Pro.local:5516/
# Release version:      24.1.0
# Date created:         Thu Oct 09 12:05:52 IST 2025

---
apiVersion: xl-release/v1
kind: Import
spec:
  imports:
  - Notifications.yaml
  - Templates.yaml
