# Exported from:        http://Kirans-MacBook-Pro.local:5516/
# Release version:      24.1.0
# Date created:         Thu Oct 09 11:24:22 IST 2025

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  path: Folder-C
  home: Test-S-116492-Templates%2FFolder-A%2FFolder-B%2FFolder-C/Folder-C
spec:
- template: Templates
  scheduledStartDate: 2025-10-09T09:00:00+05:30
  phases:
  - phase: New Phase
    tasks:
    - name: T1
      type: xlrelease.Task
    - name: T2
      type: xlrelease.Task
  riskProfile: Default risk profile
  author: admin
