# Exported from:        http://Kirans-MacBook-Pro.local:5516/
# Release version:      24.1.0
# Date created:         Mon Oct 07 17:30:56 IST 2024

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  path: /
  home: S-112756
spec:
- name: Jenkins-Local_Folder
  type: jenkins.Server
  url: http://localhost:8082/
  username: admin
  password: !value "jenkins_Server_Jenkins_Local_Folder_password"
- name: Jira-Folder
  type: jira.Server
  url: https://digitalai.atlassian.net/
  username: xlr-jira-testuser@xebialabs.com
  apiToken: !value "jira_Server_Jira_Folder_apiToken"
