# Exported from:        http://Kirans-MacBook-Pro.local:5516/
# Release version:      24.1.0
# Date created:         Mon Oct 07 17:30:56 IST 2024

---
apiVersion: xl-release/v1
kind: Import
spec:
  imports:
  - Connections.yaml
  - Template_Test_Template_T1.yaml
  - Template_Test_Template_T2.yaml
  - Template_Test_Template_T3.yaml
  - Template_Test_Template_T4.yaml
  - Variables.yaml
