# Exported from:        http://Kirans-MacBook-Pro.local:5516/
# Release version:      24.1.0
# Date created:         Mon Oct 07 17:30:56 IST 2024

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  path: /
  home: S-112756
spec:
- template: Test_Template_T1
  scheduledStartDate: 2024-10-07T09:00:00+05:30
  phases:
  - phase: New Phase
    tasks:
    - name: New task
      type: jenkins.Build
      jobName: Test
      variableMapping:
        pythonScript.jenkinsServer: "${folder.test-ref-var-folder}"
  scriptUsername: admin
  scriptUserPassword: !value "xlrelease_Release_Test_Template_T1_scriptUserPassword"
  riskProfile: Default risk profile
  author: admin
