# Exported from:        http://Kirans-MacBook-Pro.local:5516/
# Release version:      24.1.0
# Date created:         Mon Oct 07 17:30:56 IST 2024

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  path: /
  home: S-112756
spec:
- template: Test_Template_T4
  scheduledStartDate: 2024-10-07T09:00:00+05:30
  phases:
  - phase: New Phase
    tasks:
    - name: T1
      type: jira.CheckIssue
      issueId: "123456"
      expectedStatusList:
      - Done
      variableMapping:
        pythonScript.jiraServer: "${folder.jira-miras}"
  variables:
  - type: xlrelease.ReferenceVariable
    key: jira-miras
    requiresValue: false
    showOnReleaseStart: false
    referencedType: jira.Server
  scriptUsername: admin
  scriptUserPassword: !value "xlrelease_Release_Test_Template_T4_scriptUserPassword"
  riskProfile: Default risk profile
  author: admin
