# Exported from:        http://Kirans-MacBook-Pro.local:5516/
# Release version:      24.1.0
# Date created:         Fri Nov 07 12:14:15 CET 2025

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  path: Child-A/Child-B/Child-C
  home: D-41252/Child-A/Child-B/Child-C
spec:
- template: T1
  scheduledStartDate: 2025-11-07T04:30:00+01:00
  phases:
  - phase: New Phase
    tasks:
    - name: New task
      type: xlrelease.Task
  riskProfile: Default risk profile
  author: admin
