# Exported from:        http://Kirans-MacBook-Pro.local:5516/
# Release version:      24.1.0
# Date created:         Mon Sep 30 20:02:07 IST 2024

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  path: /
  home: CRTTest
spec:
- template: Parent
  scheduledStartDate: 2024-04-08T18:30:00+05:30
  dueDate: 2024-04-08T19:30:00+05:30
  phases:
  - phase: New Phase
    tasks:
    - name: ui
      type: xlrelease.UserInputTask
      description: Please enter the required information below.
      owner: admin
      variables:
      - numVal
      - boolVal
      - stringVal
      - ListBox
    - name: CreateRelease
      type: xlrelease.CreateReleaseTask
      variableMapping:
        templateVariables[3].value: "${numVal}"
        templateVariables[0].value: "${ListBox}"
        templateVariables[2].value: "${boolVal}"
      newReleaseTitle: New Release
      templateVariables:
      - type: xlrelease.StringVariable
        key: ListBox
        value: cat
      - type: xlrelease.StringVariable
        key: stringVal
        value: "${stringVal}"
      - type: xlrelease.BooleanVariable
        key: boolVal
      - type: xlrelease.IntegerVariable
        key: numVal
        value: 999
      template: ./Child
      folder: ./
  variables:
  - type: xlrelease.StringVariable
    key: ListBox
    requiresValue: false
    valueProvider:
      type: xlrelease.ListOfStringValueProviderConfiguration
      values:
      - dog
      - cat
      - bird
    value: cat
  - type: xlrelease.StringVariable
    key: stringVal
    requiresValue: false
    value: fooBar
  - type: xlrelease.BooleanVariable
    key: boolVal
    requiresValue: false
  - type: xlrelease.IntegerVariable
    key: numVal
    requiresValue: false
    value: 999
  scriptUsername: admin
  scriptUserPassword: !value "xlrelease_Release_Parent_scriptUserPassword"
  riskProfile: Default risk profile
