# Exported from:        http://Kirans-MacBook-Pro.local:5516/
# Release version:      25.3.8-628.1600
# Date created:         Wed Jul 22 12:26:34 IST 2026

---
apiVersion: xl-release/v1
kind: Import
spec:
  imports:
  - Notifications.yaml
  - Template_test_template.yaml
  - Variables.yaml
