# Exported from:        http://Kirans-MacBook-Pro.local:5516/
# Release version:      25.3.8-628.1600
# Date created:         Wed Jul 22 12:27:44 IST 2026

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  path: /
  home: D-43333_253x
spec:
- template: Test_template
  scheduledStartDate: 2026-07-22T09:00:00+05:30
  phases:
  - phase: New Phase
    tasks:
    - name: CRT1
      type: xlrelease.CreateReleaseTask
      newReleaseTitle: RAC
      template: "${folder.parent-template}"
      folder: "${folder.target-folder}"
    - name: CRT2
      type: xlrelease.CreateReleaseTask
      owner: admin
      newReleaseTitle: RAC
      template: "${folder.parent-template}"
      folder: "${folder.target-folder}"
  riskProfile: Default risk profile
  author: admin
