# Exported from:        http://Kirans-MacBook-Pro.local:5516/
# Release version:      25.3.8-628.1600
# Date created:         Wed Jul 22 12:27:44 IST 2026

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  path: /
  home: D-43333_253x
spec:
- folderVariables:
  - type: xlrelease.StringVariable
    key: folder.parent-template
  - type: xlrelease.StringVariable
    key: folder.target-folder
