# Exported from:        http://Kirans-MacBook-Pro.local:5516/
# Release version:      26.1.0
# Date created:         Wed Nov 19 06:30:07 CET 2025

---
apiVersion: xl-release/v1
kind: Import
spec:
  imports:
  - Notifications.yaml
  - Template_template-b.yaml
