# Exported from:        http://Kirans-MacBook-Pro.local:5516/
# Release version:      24.1.0
# Date created:         Wed Sep 24 17:39:52 IST 2025

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  path: /
  home: D-40773
spec:
- pattern: Test-Pattern
  stages:
  - stage: New Stage
  trackedItems:
  - trackedItem: Test-Tracked-Item
