# Exported from:        http://Kirans-MacBook-Pro.local:5516/
# Release version:      24.1.0
# Date created:         Wed Sep 24 17:39:52 IST 2025

---
apiVersion: xl-release/v1
kind: Import
spec:
  imports:
  - Notifications.yaml
  - Pattern_Test-Pattern.yaml
  - Template_Test_Template_T1.yaml
  - Trigger_Test-Trigger-01.yaml
  - Workflow_Test-Workflow_T1.yaml
