# Exported from:        http://Kirans-MacBook-Pro.local:5516/
# Release version:      24.1.0
# Date created:         Mon Jun 16 14:48:04 IST 2025

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  path: /
  home: S-121808
spec:
- template: Test_Template_T1
  scheduledStartDate: 2025-06-16T09:00:00+05:30
  phases:
  - phase: New Phase
    tasks:
    - name: T0
      type: xlrelease.Task
      owner: admin
    - name: New task
      type: xlrelease.Task
      owner: admin
    - name: T2
      type: xlrelease.Task
      owner: admin
  riskProfile: Default risk profile
  author: admin
