# Exported from:        http://Kirans-MacBook-Pro.local:5516/
# Release version:      24.1.0
# Date created:         Fri Nov 22 15:23:52 IST 2024

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  path: nested
  home: D-37260/nested
spec:
- name: Test-Git-Repo
  type: git.Repository
  url: https://github.com/Digi109Kiran/NewOneTestDAI
  username: Digi109Kiran
  password: !value "git_Repository_Test_Git_Repo_password"
- name: Jenkins-Local-Nested
  type: jenkins.Server
  url: http://localhost:8082/
  username: admin
  password: !value "jenkins_Server_Jenkins_Local_Nested_password"
