# Exported from:        http://release-nightly.devops.dev.digitalai.cloud/
# Release version:      26.3.0-beta.507

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  path: /
  home: FolderA/FolderB/FolderC
spec:
- template: TemplateDummy
  scheduledStartDate: 2026-05-07T03:30:00Z
  phases:
  - phase: New Phase
    tasks:
    - name: New task
      type: xlrelease.Task
  riskProfile: Default risk profile
  author: kiran.sureshraaj@digital.ai
