# Exported from:        http://Kirans-MacBook-Pro.local:5516/
# Release version:      24.1.0
# Date created:         Mon Oct 07 18:22:04 IST 2024

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  path: /
  home: Test-Child-KiranS-112756
spec:
- template: Test-T1
  scheduledStartDate: 2024-10-07T09:00:00+05:30
  dueDate: 2024-10-07T10:00:00+05:30
  phases:
  - phase: New Phase
    tasks:
    - name: T1
      type: jira.CheckIssue
      issueId: "123456"
      expectedStatusList:
      - Done
      variableMapping:
        pythonScript.jiraServer: "${folder.jira-folder-var}"
  scriptUsername: admin
  riskProfile: Default risk profile
  author: admin
