# Exported from:        http://Kirans-MacBook-Pro.local:5516/
# Release version:      24.1.0
# Date created:         Tue Oct 08 20:34:42 IST 2024

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  path: /
  home: Test-Parent-KiranS-112756
spec:
- template: Test-T1
  scheduledStartDate: 2024-10-07T09:00:00+05:30
  dueDate: 2024-10-07T10:00:00+05:30
  phases:
  - phase: New Phase
    tasks:
    - name: T1
      type: jira.CheckIssue
      issueId: "123456"
      expectedStatusList:
      - Done
      variableMapping:
        pythonScript.jiraServer: "${folder.jira-folder-var}"
  scriptUsername: admin
  scriptUserPassword: !value "xlrelease_Release_Test_T1_scriptUserPassword"
  riskProfile: Default risk profile
  author: admin
