# Exported from:        http://Kirans-MacBook-Pro.local:5516/
# Release version:      24.1.0
# Date created:         Mon Oct 07 18:22:04 IST 2024

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  path: /
  home: Test-Child-KiranS-112756
spec:
- folderVariables:
  - type: xlrelease.ReferenceVariable
    key: folder.jira-folder-var
    value: Configuration/Custom/Configuration3f7352995c2443febdb6c6d3f462ce7b
    referencedType: jira.Server
