# Exported from:        http://Kirans-MacBook-Pro.local:5516/
# Release version:      24.1.0
# Date created:         Tue Oct 08 20:34:42 IST 2024

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  path: /
  home: Test-Parent-KiranS-112756
spec:
- folderVariables:
  - type: xlrelease.ReferenceVariable
    key: folder.jira-folder-var
    value: JIRA-Folder
    referencedType: jira.Server
