# Exported from:        http://Kirans-MacBook-Pro.local:5516/
# Release version:      24.1.0
# Date created:         Tue Oct 07 12:10:20 IST 2025

---
apiVersion: xl-release/v1
kind: Applications
metadata:
  path: Folder-01
  home: S-116492-A%2FFolder-01/Folder-01
spec:
- name: Application-01
  type: xlrelease.Application
