# Exported from:        http://Kirans-MacBook-Pro.local:5516/
# Release version:      24.1.0

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  path: /
  home: Demo-S-125649
spec:
- template: Template_T1
  scheduledStartDate: 2025-11-25T04:30:00+01:00
  dueDate: 2025-11-25T05:30:00+01:00
  phases:
  - phase: New Phase
    tasks:
    - name: T1
      type: xlrelease.Task
    - name: T2
      type: xlrelease.Task
    - name: T3
      type: xlrelease.ScriptTask
      script: |-
        print 'Hello Line 123'
        print 'Hello Line 123'
        print 'Hello Line 123'
        print 'Hello Line 123'
        print 'Hello Line 123'
        print 'Hello Line 123'
        print 'Hello Line 123'
        print 'Hello Line 123'
        print 'Hello Line 123'
        print 'Hello Line 123'
        print 'Hello Line 456'
        print 'Hello Line 456'
        print 'Hello Line 456'
        print 'Hello Line 456'
        print 'Hello Line 123'
        print 'Hello Line 123'
        print 'Hello Line 123'
        print 'Hello Line 123'
        print 'Hello Line 123'
        print 'Hello Line 123'
        print 'Hello Line 123'
        print 'Hello Line 123'
  riskProfile: Default risk profile
  author: admin
