# Exported from:        http://LAPTOP-95VG3LUV:5516/
# Release version:      22.0.0-20211220-123974
# Date created:         Fri Mar 17 16:22:36 IST 2023

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: Test-1
spec:
- pattern: Test_Pattern_Check
  description: Test_Pattern_Check
  plannedDuration: 1
  stages:
  - stage: Stage One
    owner: admin
  - stage: Stage 2
    owner: admin
- template: T1
  scheduledStartDate: 2023-03-09T09:00:00+05:30
  dueDate: 2023-03-09T10:00:00+05:30
  phases:
  - phase: P1
    tasks:
    - name: T1
      type: xlrelease.Task
    color: '#3d6c9e'
  riskProfile: Default risk profile
- name: Test Dashboard
  type: xlrelease.BlankDashboard
  description: Test Dashboard
  owner: admin
  tiles:
  - name: Top 10 longest phases
    type: xlrelease.LongestPhasesTile
    row: 0
    col: 0
  - name: Top 10 longest releases
    type: xlrelease.LongestReleasesTile
    row: 0
    col: 3
  - name: Top 10 longest tasks
    type: xlrelease.LongestTasksTile
    row: 2
    col: 0
  - name: Top 10 task assignees
    type: xlrelease.TopTenTaskAssigneeTile
    row: 2
    col: 3
---
apiVersion: xl-release/v1
kind: Permissions
metadata:
  home: Test-1
spec:
- directory: "."
  teams:
  - name: Folder Owner
    users:
    - admin
    permissions:
    - folder#edit_variables
    - delivery_pattern#edit
    - folder#edit_configuration
    - delivery#edit
    - folder#view_versions
    - folder#apply_changes
    - group#view
    - folder#edit_versions
    - folder#edit_notifications
    - delivery_pattern#view
    - group#edit
    - delivery#view
    - delivery#edit_tracked_item
    - folder#view
    - folder#edit_security
    - dashboard#edit
    - folder#edit
    - dashboard#view
    - folder#generate_configuration
  - name: Template Owner
    users:
    - admin
    permissions:
    - template#create_release_other_folder
    - template#edit
    - trigger#view_trigger
    - template#lock_task
    - template#view
    - folder#view
    - template#edit_security
    - template#create_release
    - template#edit_triggers
    - template#edit_precondition
    - template#edit_failure_handler
  - name: Release Admin
    users:
    - admin
    permissions:
    - release#edit_precondition
    - release#edit
    - release#advance_task_transition
    - release#edit_security
    - release#restart_phase
    - release#lock_task
    - folder#view
    - release#edit_task_script
    - release#edit_task_configuration_facet
    - release#edit_task_flag
    - release#edit_task_dates
    - release#edit_task
    - release#edit_task_attachments
    - release#task_transition
    - trigger#view_trigger
    - release#reassign_task
    - release#edit_task_input_output_properties
    - release#edit_task_tags
    - release#edit_task_description
    - trigger#edit_trigger
    - release#view
    - release#start
    - release#edit_blackout
    - release#edit_failure_handler
    - release#abort
