# Exported from:        http://LAPTOP-95VG3LUV:5516/
# Release version:      22.0.0-20211220-123974
# Date created:         Thu Apr 13 16:35:56 IST 2023

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: S-91883
spec:
- pattern: Pattern _t1
  description: Pattern _t1
  plannedDuration: 1
  stages:
  - stage: New Stage
