# Exported from:        http://Kirans-MacBook-Pro.local:5516/
# Release version:      24.1.0
# Date created:         Mon Jul 21 17:12:24 IST 2025

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  path: /
  home: S-121806
spec:
- folderVariables:
  - type: xlrelease.ReferenceVariable
    key: folder.jenkins-ref-var
    value: Jenkins-Local_Doc
    referencedType: jenkins.Server
